services:
  - type: web
    name: sistema-fadlo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn setup_sistema.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: setup_sistema.settings
      - key: PYTHON_VERSION
        value: 3.13
